"""
    This module provides all the task1, subtask A and B models.
"""

from .base import evaluate_task1_subtaska_worker, evaluate_task1_subtaskb_worker
from .dummy import BEST_TASK1_SUBTASKA, BEST_TASK1_SUBTASKB, WORST_TASK1_SUBTASKA, \
    WORST_TASK1_SUBTASKB, RANDOM_TASK1_SUBTASKA, RANDOM_TASK1_SUBTASKB, CONSERVATIVE
from .vgg256 import VGG256_IMAGENET, VGG256_IMAGENET_PLACES2
from .wrappers import Wrapper, WRAPPER_CLASSIFIERS

# Task 1 models
## Task 1, subtask A models
DUMMY_TASK1_SUBTASKA_MODELS = [BEST_TASK1_SUBTASKA, WORST_TASK1_SUBTASKA, RANDOM_TASK1_SUBTASKA]
NONDUMMY_TASK1_SUBTASKA_MODELS = [VGG256_IMAGENET, VGG256_IMAGENET_PLACES2]
TASK1_SUBTASKA_MODELS = DUMMY_TASK1_SUBTASKA_MODELS + NONDUMMY_TASK1_SUBTASKA_MODELS

## Task 1, subtask B models
DUMMY_TASK1_SUBTASKB_MODELS = [BEST_TASK1_SUBTASKB, WORST_TASK1_SUBTASKB, RANDOM_TASK1_SUBTASKB,
                               CONSERVATIVE]
WRAPPER_TASK1_SUBTASKB_MODELS = [Wrapper(classifier, model) \
                                 for model in NONDUMMY_TASK1_SUBTASKA_MODELS \
                                 for classifier in WRAPPER_CLASSIFIERS]
NONDUMMY_TASK1_SUBTASKB_MODELS = WRAPPER_TASK1_SUBTASKB_MODELS
TASK1_SUBTASKB_MODELS = DUMMY_TASK1_SUBTASKB_MODELS + NONDUMMY_TASK1_SUBTASKB_MODELS
